import type { Metadata } from 'next'
import { DM_Sans, Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-heading' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='h-full antialiased'>
      <body
        className={`${inter.variable} ${dmSans.variable} font-sans bg-cream text-charcoal min-h-full flex flex-col`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
